version: "3.5"

services:
  database:
    image: postgres:14.1
    container_name: database
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./.env
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend/
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./.env
    volumes:
      - ./frontend:/frontend/
    ports:
      - "5173:5173"

  gateway:
    build: ./gateway
    container_name: gateway
    env_file:
      - ./.env
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend

volumes:
  db_data: