version: "3.5"

services:
  database:
    image: postgres:14.1
    container_name: court_database
    # env_file:
    #   - ./.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data

  backend:
    build: ./backend
    container_name: court_backend
    # env_file:
    #   - ./.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend/
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: court_frontend
    # env_file:
    #   - ./.env
    volumes:
      - ./frontend:/frontend/
    ports:
      - "5173:5173"

  gateway:
    build: ./gateway
    container_name: court_gateway
    # env_file:
    #   - ./.env
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend

volumes:
  db_data: